### PR TITLE
OKTA-689219 : Updating authenticator button aria labels

### PR DESCRIPTION
**Pull request by glenfannin-okta**
## Description:
The purpose of this PR is to correct the spelling on some authenticator button i18n keys and add new dedicated keys/labels for OV method types to provide more context to users utilizing a screenreader. 

## PR Checklist

- [x] Have you verified the basic functionality for this change?
- [x] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [x] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [ ] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-689219](https://oktainc.atlassian.net/browse/OKTA-689219)

### CODE REVIEW

**Review by shuowu-okta — DISMISSED** [review]

**Comment by trevoring-okta** [comment]
One thing I noticed that should probably be added at some point with all of these updates to `AuthenticatorButton` aria labels is that lots of the transformer tests in `src/v3/src/transformer/selectAuthenticator` now have TS errors because `ariaLabel` was added as a required prop but many of the mock auth button objects that were not updated to have an `ariaLabel`

**Comment by trevoring-okta** [comment]
Another somewhat related question that I've been curious about since I've been encountering a lot of merge conflicts with `AuthenticatorButton` is why we don't have `aria-labelledby` set to `{`${iconName}-label`}` on the authenticator button component?

**Comment by glenfannin-okta** [comment]
> One thing I noticed that should probably be added at some point with all of these updates to `AuthenticatorButton` aria labels is that lots of the transformer tests in `src/v3/src/transformer/selectAuthenticator` now have TS errors because `ariaLabel` was added as a required prop but many of the mock auth button objects that were not updated to have an `ariaLabel`. If that could be fixed in this PR it would probably prevent confusion in the future and create a cleaner Git history. Otherwise, LGTM!

Done, I didn't even notice those tests had TS errors, I forget I have to open the v3 workspace directly to see reported TS errors.

**Comment by glenfannin-okta** [comment]
> Another somewhat related question that I've been curious about since I've been encountering a lot of merge conflicts with `AuthenticatorButton` is why we don't have `aria-labelledby` set to `{`${iconName}-label`}` on the authenticator button component?

In Gen 3, we were doing that, however, the label didn't provide enough context to screen readers (eg. hovering a button, the reader would just say "Email" or "Enter a code" which doesn't make sense, but "Select Email." or "Select phone" made much more sense), and since we also had to do this in Gen 2, we felt adding labels that provide clear instructions and match the labels between both generations were the proper way to go.

**Review by trevoring-okta — APPROVED** [review]

**Pull request merged**
