### PR TITLE
:bug: Change type from ‘text’ to ‘number’ in textboxes for number vaues.

### PR DESCRIPTION
**Pull request by alexeystadnikov-okta**
Resolves OKTA-79239.

Android:
176bda40-c6db-11e6-9c50-24c8aff98a55
178a3b8e-c6db-11e6-9f8f-0bf67fcb2e5b

iPhone:

iPad:

Alerts were taken by the code in `TextBox:postRender`:
```
input.blur(function () {
          alert(this.value);
        });
```

@mauriciocastillosilva-okta 
@lboyette-okta 

Please, review.

### CODE REVIEW

**Comment by marksztainbok-okta** [comment]
Looks like just changing the type number allows floating point values and does not actually display the correct keyboard.
http://stackoverflow.com/questions/6178556/phone-numeric-keyboard-for-text-input/31619311#31619311 has a better solution

**Comment by mauriciocastillosilva-okta** [comment]
Can you attach a screenshot? Changes look good to me, but that post that Mark shared says that it might not work.

**Comment by alexeystadnikov-okta** [comment]
Screenshots added.

Also added attributes `pattern` and `inputmode` to the input when `TextBox` has type 'number'.

**Comment by marksztainbok-okta** [comment]
Have you checked on both Android and iOS? Also does a MFA code like 012345 work? From what I've read there may be issues with leading 0's potentially

**Comment by alexeystadnikov-okta** [comment]
Checked with Android and iOS devices (screenshots added).
`01234` works fine. It removes first zero only on Mac/PC if use the up/down arrows.

**Pull request merged**
