### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by woodcockjosh**
## Description:

Add typescript types to project
Enable ES module style imports

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [ ] Added unit tests?
N/A

- [ ] Added e2e tests
N/A

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
N/A

### Issue:

- https://github.com/okta/okta-signin-widget/issues/1330

### CODE REVIEW

**Comment by robertjd** [comment]
Hi @woodcockjosh , thanks for the contribution!  We have been making progress towards TS support, most of it in the authJS library.  We'll need some time to review this and will get back to you. Internal ref: OKTA-334456

**Comment by hckhanh** [comment]
Is there anything new? I am wating for this PR since I am working on the TS react project.

**Comment by aarongranick-okta** [comment]
@hckhanh We are still evaluating the best way to publish type information for the signin widget. In the meantime, you should be able to easily add "ambient" type declarations in your own project to provide hints to the typescript compiler. https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules

The types defined in this PR may help, but you should leave off the "export" keyword since your project would not be exporting these types, but only using them internally during TS compilation.

**Comment by denysoblohin-okta** [comment]
Thanks for this PR
I've extended type definitions, added lint and tests
https://github.com/okta/okta-signin-widget/pull/1740

**Comment by aulttd01** [comment]
Any updates on this?

**Comment by mkorpela** [comment]
Any more updates?

**Comment by flying-sheep** [comment]
Here’s my preliminary version:

```ts
declare module '@okta/okta-signin-widget' {
  import { OktaAuth, OktaAuthOptions, Tokens } from '@okta/okta-auth-js'

  export interface ExternalIdentityProvider {
    id: string
    type?: 'GOOGLE' | 'FACEBOOK' | 'APPLE' | 'MICROSOFT' | 'LINKEDIN'
    text?: string
    className?: string
  }

  export interface OktaSignInConfig {
    // Basic

    /** The base URL for your Okta organization */
    baseUrl: string
    /** Local path or URL to a logo image that is displayed at the top of the Sign-In Widget */
    logo?: string
    /** Text for alt attribute of the logo image, logo text will only show up when logo image is not avaiable */
    logoText?: string
    /** Support phone number that is displayed in the Password Reset and Unlock Account flows. If no number is provided, no support screen is shown to the user. */
    helpSupportNumber?: string
    /** The brand or company name that is displayed in messages rendered by the Sign-in Widget (for example, "Reset your {brandName} password"). If no brandName is provided, a generic message is rendered instead (for example, "Reset your password"). You can further customize the text that is displayed with language and text settings. */
    brandName?: string

    // OpenID Connect (OIDC)

    /** Client Id of the application. Required for OIDC flow. If this option is not set, all other options in this section are ignored. */
    clientId?: string
    /** For redirect flows, this URI will be used as the callback url. If no redirectUri is provided, defaults to the current origin. */
    redirectUri?: string
    /** External Identity Providers to use in OIDC authentication, also known as Social Login. Supported IDPs are declared with a `type` and will get distinct styling and default i18n text, while any other entry will receive a general styling and require text to be provided. Each IDP can have additional CSS classes added via an optional `className` property. */
    idps?: ExternalIdentityProvider[]
    /** Display order for external identity providers relative to the Okta login form. Defaults to 'SECONDARY'. */
    idpDisplay?: 'PRIMARY' | 'SECONDARY'
    /** Timeout for OIDC authentication flow requests, in milliseconds. If the authentication flow takes longer than this timeout value, an error will be thrown and the flow will be cancelled. Defaults to 12000. */
    oAuthTimeout?: number
    /** An `AuthJS` instance. This will be available on the widget instance as the `authClient` property. Note: If the `authClient` option is used, `authParams` will be ignored. */
    authClient?: OktaAuth
    /** An object containing configuration which is used to create the internal authClient`. Selected options are described below. See the full set of Configuration options */
    authParams?: OktaAuthOptions
  }

  export interface ShowSignInOptions {
    /** CSS selector which identifies the container element that the widget attaches to. If omitted, defaults to the value passed in during the construction of the Widget.*/
    el?: string
    /** Client Id pre-registered with Okta for the OIDC authentication flow. If omitted, defaults to the value passed in during the construction of the Widget. */
    clientId?: string
    /** The url that is redirected to after authentication. This must be pre-registered as part of client registration. Defaults to the current origin.*/
    redirectUri?: string
  }

  export interface ScopedShowSignInOptions extends ShowSignInOptions {
    /** Specify what information to make available in the returned access or ID token. If omitted, defaults to the value of authParams.scopes passed in during construction of the Widget. Defaults to ['openid', 'email'] */
    scopes?: string[]
  }

  export type SigninWidgetEvent = 'ready' | 'afterError' | 'afterRender'
  export interface SigninWidgetEventCallback {
    (
      context: { controller: string },
      error?: {
        name: string
        message: string
        statusCode?: number
        xhr?: any
      },
    ): any
  }

  export default class OktaSignIn {
    constructor(config: OktaSignInConfig)
    /** Returns a Promise. Renders the widget to the DOM to prompt the user to sign in. On successful authentication, the Promise will be resolved to an object containing OAuth tokens. */
    showSignInToGetTokens(options: ScopedShowSignInOptions): Promise<Tokens>
    /** Returns a Promise. Renders the widget to the DOM to prompt the user to sign in. On successful authentication, the browser will be redirected to Okta with information to begin a new session. Okta's servers will process the information and then redirect back to your application's redirectUri. If succesful, an authorization code will exist in the URL as the "code" query parameter. If unsuccesful, there will be an "error" query parameter in the URL. */
    showSignInAndRedirect(options: ShowSignInOptions): Promise<void>
    /** Returns a Promise. Renders the widget to the DOM. On success, the promise will resolve. On error, the promise will reject. Also accepts a success or error callback function. */
    renderEl(
      options: { el?: string },
      success?: (opts: any) => any,
      error?: (err: Error) => any,
    ): Promise<any>
    /** Hide the widget, but keep the widget in the DOM. */
    hide(): void
    /** Show the widget if hidden. */
    show(): void
    /** Remove the widget from the DOM entirely. */
    remove(): void
    /** Subscribe to an event published by the widget. */
    on(event: SigninWidgetEvent, callback: SigninWidgetEventCallback): void
    /** Unsubscribe from widget events. If no callback is provided, unsubscribes all listeners from the event. */
    off(event?: SigninWidgetEvent, callback?: SigninWidgetEventCallback): void
    /** The underlying @okta/okta-auth-js object used by the Sign-in Widget. All methods are documented in the AuthJS base library. */
    authClient: OktaAuth
  }
}
```

**Comment by cdierkens** [comment]
Also interested in this PR

**Comment by richmason** [comment]
Hoping this will be added soon...

**Comment by aarongranick-okta** [comment]
@woodcockjosh Thank you very much for this submission. We took the request for Typescript support very seriously and have added type definitions to all of our major Javascript SDKs, including okta-signin-widget. Types were added to the widget in version 6.3.0. The latest version has the latest type definitions and all other fixes. Please let us know if you find a problem with any of your type definitions. Thanks again!

**Pull request closed without merging**
