### PR TITLE
OKTA-367808: SIW a11y improvement

### PR DESCRIPTION
**Pull request by lesterchoi-okta**
## Description:

* convert authenticator list from `<div>` elements to `<ul>` and `<li>`

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

### Issue:

- [OKTA-367808](https://oktainc.atlassian.net/browse/OKTA-367808)

### CODE REVIEW

**Comment by haishengwu-okta** [comment]
This is for v2. I believe the JIRA is asking to fix something for v1.

**Comment by lesterchoi-okta** [comment]
> This is for v2. I believe the JIRA is asking to fix something for v1.

Got it. Thanks for the quick redirect, I'll find it.

**Comment by lesterchoi-okta** [comment]
@haishengwu-okta updated to apply change to v1 FactorList component.
Change is small, but I had to dig pretty deep to figure out how to view/test v1 SIW.
Could add some notes to `readme.md` and/or `.widgetrc.sample.js`?

**Review by haishengwu-okta — APPROVED** [review]
- Could you add screenshot to demonstrate no regression look-n-feel?
- Curious if you double check with any a11y automation tool or screen reader?

**Comment by lesterchoi-okta** [comment]
@haishengwu-okta 

Used VoiceOver to check the behavior. Changing to `<ul><li>` reads out "list 1 of 1" whereas the `<div><div>` version just goes through the headings.

**Sidenote**: axe a11y check integration is already in the repo, how can I enable this?
https://github.com/okta/okta-signin-widget/blob/master/test/e2e/util/Expect.js#L26-L39

No visual regression:

Before


After

**Comment by haishengwu-okta** [comment]
`toBeA11yCompliant` is used for e2e testing which I doubt it covers the factor selection page.
We need better test coverage for SIW for sure. would be follow up ticket.

**Pull request closed without merging**
