### PR TITLE
:bug: Changed border color on focused button

### PR DESCRIPTION
**Pull request by eugenebakaiev-okta**
Added variable for focused input color
Resolves: OKTA-117073

### CODE REVIEW

**Comment by eugenebakaiev-okta** [comment]
buttonfocus mov

**Comment by eugenebakaiev-okta** [comment]
@hor-kanchan-okta please take a look

**Comment by eugenebakaiev-okta** [comment]
@mauriciocastillosilva-okta, could you please take a look?

**Comment by mauriciocastillosilva-okta** [comment]
Also, please change the commit message to present tense (https://github.com/alanzhou-okta/conventional-github-releaser-okta/blob/master/CONTRIBUTING.md)

**Comment by eugenebakaiev-okta** [comment]
@mauriciocastillosilva-okta checked, it's okay, there's no impacts on my fix in _btns.scss.

**Pull request merged**
