### PR TITLE
:package: Replace unmaintained jquery.cookie library with js-cookie

### PR DESCRIPTION
**Pull request by johnantoni**
:package: Replace outdated jquery.cookie library with js-cookie

Removed **jquery.cookie** library https://github.com/carhartl/jquery-cookie
Replaced with **js-cookie** https://github.com/js-cookie/js-cookie
Updated **CookieUtil.js** which uses jquery.cookie to use the new get/set methods of js-cookie
Updated **webpack.release.config.js** to reference js-cookie

Resolves: Done in order to help resolve github issue https://github.com/okta/okta-signin-widget/issues/380

Let me know if I missed anything ;-)

### CODE REVIEW

**Comment by johnantoni** [comment]
Attempted to resolve the Travis errors, still got a couple regarding Cookie() not available on Jasmine, any chance someone can have a look and see where I've gone wrong?

**Comment by mraible** [comment]
@johnantoni Can you please rebase so the files in your PR are up-to-date?

**Comment by johnantoni** [comment]
ok, done. screwed it up the first time as it's been a while.

**Comment by mraible** [comment]
Thanks @johnantoni! This widget is used for Okta Hosted Login as well, so we'll need to do some tests internally to make sure this works there too.

**Comment by johnantoni** [comment]
no problem, chat later @mraible

**Comment by pydanny** [comment]
This is a complete blocker for us to use Okta. Any movement on this?

**Comment by johnantoni** [comment]
Hi @pydanny, if one of the Okta team can take this over maybe @mraible that'd be awesome. Switched projects and pretty busy right now to continue on this.

Sorry

**Comment by mraible** [comment]
Hello @johnantoni. I don't have commit rights to this repo, but maybe @jmelberg-okta or @robertdamphousse-okta can help you out.

**Comment by jmelberg-okta** [comment]
We're happy to say this fix has now been included with the `2.10.0` version.

Closing this down as changes were captured in #467

**Pull request closed without merging**
