### PR TITLE
feat: preserve username when navigating to forgot password page

### PR DESCRIPTION
**Pull request by jiashuChen**
## Description:
If user has already entered username on the login page, we could try to preserve the username when they navigate to the forgot password page.

Current behaviour would see the username cleared when navigating from the main login screen to forgot password.

### Screenshot/Video:
Current Behaviour:

https://user-images.githubusercontent.com/4397605/148003632-c7bd7003-ff0c-42c9-a2a5-087bd036b5f5.mov

Proposed new change:

https://user-images.githubusercontent.com/4397605/148003844-822e5e21-7133-4a1f-ba7d-3600c123be64.mov

### CODE REVIEW

**Comment by aarongranick-okta** [comment]
@jiashuChen thanks for the feature suggestion. cc @deepamahalingam-okta

**Comment by jiashuChen** [comment]
> @jiashuChen thanks for the feature suggestion. cc @deepamahalingam-okta

hi @deepamahalingam-okta  any update for this pr?

**Review by aarongranick-okta — APPROVED** [review]
lgtm. Someone from Okta can merge this for the next feature release (late Feb)

**Comment by deepamahalingam-okta** [comment]
Thanks for this PR @jiashuChen

**Comment by robertdamphousse-okta** [comment]
Thanks @jiashuChen for the PR!  While are waiting for this to be picked up in the next release, can you please submit a CLA request for your contribution, you can find the instructions here: https://developer.okta.com/cla/

Thanks!

**Comment by jiashuChen** [comment]
> Thanks @jiashuChen for the PR! While are waiting for this to be picked up in the next release, can you please submit a CLA request for your contribution, you can find the instructions here: https://developer.okta.com/cla/
> 
> Thanks!

Hi @robertdamphousse-okta,

Sorry for the late reply, but I've signed the CLA and emailed to [CLA@okta.com](mailto:CLA@okta.com) as directed in the link you provided.

**Comment by jiashuChen** [comment]
rebased with okta:master to resolve conflicts

**Pull request closed without merging**
