### PR TITLE
:arrow_up: Update courage to 2.1.0

### PR DESCRIPTION
**Pull request by mauriciocastillosilva-okta**
- Also updated install-with-shrinkwrap to 1.6.0 (does not run dedupe)

Resolves: OKTA-119240
Bacon: test

### CODE REVIEW

**Comment by richardheng-okta** [comment]
Can the failing check for the build be resolved?

**Comment by rchild-okta** [comment]
FYI the reason this is probably failing is because of [this commit](https://github.com/okta/courage/commit/0f359536ef6a5b371450dabde1374c045a94888a), which requires some changes to the widget.

**Comment by mauriciocastillosilva-okta** [comment]
I see... and this is the [commit](https://github.com/okta/okta-core/commit/b294c2a9094577a6463c95630ad48c32d34d340e) in okta-core which can probably be a guideline on what we need to do here.

**Comment by mauriciocastillosilva-okta** [comment]
closing since changes were merged in https://github.com/okta/okta-signin-widget/pull/199

**Pull request closed without merging**
