### PR TITLE
spike: g3 ie11 compat 

### PR DESCRIPTION
**Pull request by shuowu-okta**
## Description:

* bundles g3 with webpack, leave vite for development
* adds g3 playground to test cdn bundle (yarn start:playground)
* fixes css logical properties ie11 compat issue & updated eslint config
* follow up style fixes will be added in another PR

Identify view screenshot in IE11
Screen Shot 2023-06-15 at 4 29 54 PM

## PR Checklist

- [ ] Have you verified the basic functionality for this change?
- [ ] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [ ] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by glenfannin-okta** [comment]
Can you point this branch at https://github.com/okta/okta-signin-widget/tree/okta-600908-05-to-master-merge since the merge to master branch has all of the bacon suites enabled? 

I dont think there should be any conflicts since it the merge to master branch does change any of the components 🙏

**Comment by shuowu-okta** [comment]
@glenfannin-okta Thanks for the reminder, I'll rebase against master (and re-point) once 0.5 is merged.

**Comment by shawyu-okta** [comment]
Rebased on `master` and pushed

**Comment by shawyu-okta** [comment]
Closed in #3325.

**Pull request closed without merging**
