### PR TITLE
chore: expose root mocks as workspace

### PR DESCRIPTION
**Pull request by shuowu-okta**
## Description:

This PR can be taken as the first step to using root mocks in jest integration tests, so both v2 and v3 follows the same mocks.

Changes:

* exposes root mocks as yarn workspace, so it can be referred as a isolated module from v3
* update `enroll-profile` jest integration test with new mock from @okta/mocks

## PR Checklist

- [ ] Have you verified the basic functionality for this change?
- [ ] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [ ] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-522967](https://oktainc.atlassian.net/browse/OKTA-522967)

### CODE REVIEW

**Review by lesterchoi-okta — CHANGES_REQUESTED** [review]
This should be a change to webpack configs for alias module resolution

**Comment by shuowu-okta** [comment]
@lesterchoi-okta why webpack config matters? this is for jest, and I don't see issue with making mocks as a workspace package.

**Comment by lesterchoi-okta** [comment]
> @lesterchoi-okta why webpack config matters? this is for jest, and I don't see issue with making mocks as a workspace package.

Then it should be a change to `jest.config.js` `moduleNameMapper`, right? Why do you need to add another workspace? There are no dependencies in the package.json and this change appears just to make the import path simpler.

**Comment by shuowu-okta** [comment]
mostly to avoid the complex relative path pattern, and I do feel this is the proper pattern to use external modules (outside of v3), if we config moduleMapper, code still will be changed when folder changes, but one isolated workspace can just avoid all future changes. If you search in the repo, you will find @okta/env is used the same way. It's actually the real power of using monorepo.

**Review by lesterchoi-okta — APPROVED** [review]
discussed offline. using workspace pattern is fine since there is precedent, e.g., `@okta/env`

**Pull request merged**
