### PR TITLE
OKTA-826772 add new grace period translation strings

### PR DESCRIPTION
**Pull request by TiffanyNg-okta**
## Description:
- Adding new translation strings ahead of time to support grace periods for authenticator enrollment
- Implementation will be done separately
- Figma: https://www.figma.com/design/lOOqLOMOii5l6lIbYCvUKz/Authenticator-enrollment-campaigns?node-id=44-2739&t=ZOcil7rhooxG74XI-4

## PR Checklist

- [ ] Have you verified the basic functionality for this change?
- [ ] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [ ] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-826772](https://oktainc.atlassian.net/browse/OKTA-826772)

### CODE REVIEW

**Comment by shawyu-okta** [comment]
@TiffanyNg-okta make sure your comments are "Verified" with PGP and force push this branch (all commits need to be verified to merge)

**Comment by TiffanyNg-okta** [comment]
@shawyu-okta Commit should be verified now

**Review by shawyu-okta — DISMISSED** [review]
Please also get approval from @shuowu-okta

**Review by shawyu-okta — APPROVED** [review]
lgtm, needs review from @shuowu-okta

**Review by alexchen-okta — APPROVED** [review]

**Pull request merged**
