### PR TITLE
fix: read cancel polling value from currentAuthenticator object

### PR DESCRIPTION
**Pull request by yannongli-okta**
## Description:

There was a change in API response that device authenticator challenge context is moved from `currentAuthenticatorEnrollment` to `currentAuthenticator`. The SIW needs to accommodate this change in loopback server method to get the cancel polling form from `currentAuthenticator`. This PR implements following things:

1. Change the place to get cancel polling form 
2. Update mock api response files to reflect latest api from backend
3. Remove UserVerificationDeviceChallengeView since it was no longer used and replaced by ChallengeOktaVerifyFastPassView. Also renamed testcafe tests
4. No new tests needs to be updated since existing tests is already covering the flow.

The reason that this flow was broken and remains undetected for months is: both SIW and backend is simulating what other side is doing. In backend api tests, we assume SIW to use latest API contract. While in SIW side, the tests is using the legacy API contract. We will have a RCA for this and dive deep to see how to prevent this from happening again.

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:

https://okta.box.com/s/uj1364ihlkhpnmbit3my1exq6ye2mrmd

### Reviewers:

@jhe-okta @gowthamidommety-okta 

### Issue:

- [OKTA-348362](https://oktainc.atlassian.net/browse/OKTA-348362)

### CODE REVIEW

**Review by jhe-okta — APPROVED** [review]
The changes look good. What about the OV as a MFA case? Is the API response different from the user verification responses?

**Comment by yannongli-okta** [comment]
> The changes look good. What about the OV as a MFA case? Is the API response different from the user verification responses?

Yeah the responses are different especially with the currentAuthenticator object. But in general they have the same structure with `authenticators`, `authenticatorEnrollments` and `currentAuthenticator`.
The API response are like: https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/data/idp/idx/authenticator-verification-okta-verify-totp.json and https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/data/idp/idx/authenticator-verification-okta-verify-push.json

**Comment by jhe-okta** [comment]
> > The changes look good. What about the OV as a MFA case? Is the API response different from the user verification responses?
> 
> Yeah the responses are different especially with the currentAuthenticator object. But in general they have the same structure with `authenticators`, `authenticatorEnrollments` and `currentAuthenticator`.
> The API response are like: https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/data/idp/idx/authenticator-verification-okta-verify-totp.json and https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/data/idp/idx/authenticator-verification-okta-verify-push.json

@yannongli-okta Can you add a mock (any approach is fine with me) and update responseConfig with a flow for MFA list?

**Comment by yannongli-okta** [comment]
> > > The changes look good. What about the OV as a MFA case? Is the API response different from the user verification responses?
> > 
> > 
> > Yeah the responses are different especially with the currentAuthenticator object. But in general they have the same structure with `authenticators`, `authenticatorEnrollments` and `currentAuthenticator`.
> > The API response are like: https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/data/idp/idx/authenticator-verification-okta-verify-totp.json and https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/data/idp/idx/authenticator-verification-okta-verify-push.json
> 
> @yannongli-okta Can you add a mock (any approach is fine with me) and update responseConfig with a flow for MFA list?

@jhe-okta I believe this mock https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/config/responseConfig.js#L356 and the `ov challenge` mocks below it are for MFA use cases.
But i think i can add a similar json file called `authenticator-verification-okta-verify-signed_nonce.json` and a new mock similar to MFA use cases.

**Comment by jhe-okta** [comment]
> https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/config/responseConfig.js#L356
Yes, adding one for signed nonce is good.

**Review by gowthamidommety-okta — APPROVED** [review]
lgtm - thank you for the detailed description!

**Pull request closed without merging**
