### PR TITLE
port: siw-next@c316c34f - use MUI, remove JSONForms, bugfix, OktaSignIn events

### PR DESCRIPTION
**Pull request by lesterchoi-okta**
## Description:

port changes from siw-next@c316c34f which includes 

- MUI siw-next@c316c34f
- event siw-next@cf38d0d9
- bugfix siw-next@12a15df4
- jsonforms siw-next@2cfa930a

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [x] Added unit tests?

- [x] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

- Did you verify the change by running downstream monolith artifacts? (YES | NO | UNSURE)

### Issue:

- [OKTA-513903](https://oktainc.atlassian.net/browse/OKTA-513903)

### CODE REVIEW

**Review by shawyu-okta — APPROVED** [review]
looks like TS issues

**Comment by shuowu-okta** [comment]
How about rebasing 0.0 against master, then rebase this one against 0.0, so we can end up with a cleaner history. It might can avoid unnecessary issues when merge 0.0 back to master.

**Review by glenfannin-okta — APPROVED** [review]

**Comment by lesterchoi-okta** [comment]
>  How about rebasing 0.0 against master, then rebase this one against 0.0, so we can end up with a cleaner history. It might can avoid unnecessary issues when merge 0.0 back to master.

Yes, that's the plan. #2603 is the `0.0` rebase on `master`

**Comment by lesterchoi-okta** [comment]
@shuowu need an approval from CODEOWNER. From Bacon:
> Make sure you have all required CODEOWNERS approve your commit and have no reviewers requiring changes. Additionally ensure all Github Actions are passing . View the PR for more info.

**Review by shuowu-okta — APPROVED** [review]

**Review by leemchale-okta — APPROVED** [review]

**Pull request merged**
