### PR TITLE
OKTA-99168 New Signin Flow does not provide adequate visual indication - violation of Section 508 and WCAG 2

### PR DESCRIPTION
**Pull request by eugenebakaiev-okta**
Added css class for focused text input, added handlers for focusin and focusout events

### CODE REVIEW

**Comment by eugenebakaiev-okta** [comment]
@rchild-okta, could you please review my pull request?

**Comment by rchild-okta** [comment]
@eugenebakaiev-okta couple things:

1. Add a screencast showing what this change looks like
2. For the public repos, we use Travis CI to run our integration tests. You can see a message above this where it says "All cehcks have failed" - that means that you have an error. When you click in, you can see what the error is (it takes you [here](https://travis-ci.org/okta/okta-signin-widget/builds/155939990))
3. Tests! Most changes you'll be making will require adding tests to verify the code that you're adding. In this case, we probably want some simple tests like "it toggles the focus-input class on focus in and focus out"

**Comment by rchild-okta** [comment]
Also, some notes on the commit message:

1. Don't include the jira number in the commit title - add it later as a "RESOLVES OKTA-1234"
2. First line of the commit message should be less than 60 characters (this is the line limit which github shows)
3. Extra information should be added after that. Line length should be less than 80 characters for subsequent lines.

Check out [this commit](https://github.com/okta/okta-signin-widget/commit/ac3c619330355a55abf6f76ffd28c795526e0e12) (or most other commits) for examples of what it should look like.

**Comment by eugenebakaiev-okta** [comment]
textbox_highlighted mov

**Comment by eugenebakaiev-okta** [comment]
@rchild-okta, 
it's weird that travis-ci build fails, i tried to run grunt btest task locally and it passes 
screen shot 2016-08-30 at 2 32 41 pm
screen shot 2016-08-30 at 2 34 11 pm

**Comment by eugenebakaiev-okta** [comment]
@rchild-okta, could you look please?

**Comment by codeboxx** [comment]
lgtm 🚀

**Comment by rchild-okta** [comment]
Looks good to me 🚀 

You'll need to rebase off of master before I can merge it in - @alexeystadnikov-okta did this recently, ask him if you have questions about how to do this.

**Pull request merged**
