### PR TITLE
Update README Header

### PR DESCRIPTION
**Pull request by jmelberg-okta**
### Description
Updates the README to follow our new template by adding the following sections:

- Getting Started
- Usage guide
- API reference
- Contributing

> Note: A follow-up PR will include more changes to improve readability.

#### Primary Reviewers
- @haishengwu-okta

### CODE REVIEW

**Comment by haishengwu-okta** [comment]
1. add the link to dev forum is cool!
2. here is the auto generated toc I got (vs code markdown plugin). 
I vote for auto generating ToC since manual maintain likely to have mistake and cumbersome. :)
Regarding the levels, given the complexity of the doc, 3 levels seems good to me unless we move `API reference` to a separated markdown file. Thoughts?

```
- [Okta Sign-In Widget](#okta-sign-in-widget)
  - [Need help?](#need-help)
  - [Getting started](#getting-started)
  - [Usage guide](#usage-guide)
  - [Browser support](#browser-support)
  - [API Reference](#api-reference)
    - [Install](#install)
      - [Using the Okta CDN](#using-the-okta-cdn)
      - [Using the npm module](#using-the-npm-module)
    - [API](#api)
      - [new OktaSignIn(config)](#new-oktasigninconfig)
      - [renderEl(options, success, error)](#rendereloptions-success-error)
      - [`OIDC` showSignInToGetTokens(options)](#oidc-showsignintogettokensoptions)
      - [hide](#hide)
      - [show](#show)
      - [remove](#remove)
      - [on(event, callback[, context])](#onevent-callback-context)
      - [off([event, callback])](#offevent-callback)
      - [getTransaction(stateToken)](#gettransactionstatetoken)
      - [session.get(callback)](#sessiongetcallback)
      - [session.refresh(callback)](#sessionrefreshcallback)
      - [session.close(callback)](#sessionclosecallback)
      - [`OIDC` token.hasTokensInUrl()](#oidc-tokenhastokensinurl)
      - [`OIDC` token.parseTokensFromUrl(success, error)](#oidc-tokenparsetokensfromurlsuccess-error)
      - [`OIDC` tokenManager.add(key, token)](#oidc-tokenmanageraddkey-token)
      - [`OIDC` tokenManager.get(key)](#oidc-tokenmanagergetkey)
      - [`OIDC` tokenManager.remove(key)](#oidc-tokenmanagerremovekey)
      - [`OIDC` tokenManager.clear()](#oidc-tokenmanagerclear)
      - [`OIDC` tokenManager.refresh(key)](#oidc-tokenmanagerrefreshkey)
      - [`OIDC` tokenManager.on(event, callback[, context])](#oidc-tokenmanageronevent-callback-context)
      - [`OIDC` tokenManager.off(event[, callback])](#oidc-tokenmanageroffevent-callback)
    - [Configuration](#configuration)
      - [Basic config options](#basic-config-options)
      - [Username and password](#username-and-password)
      - [Language and text](#language-and-text)
      - [Links](#links)
        - [Help Links](#help-links)
        - [Sign Out Link](#sign-out-link)
      - [Buttons](#buttons)
        - [Custom Buttons](#custom-buttons)
        - [Registration Button](#registration-button)
      - [Registration](#registration)
      - [Use the default error](#use-the-default-error)
      - [Use form level error](#use-form-level-error)
      - [Use field level error](#use-field-level-error)
      - [IdP Discovery](#idp-discovery)
        - [Additional configuration](#additional-configuration)
        - [Additions in the success callback](#additions-in-the-success-callback)
        - [OpenID Connect](#openid-connect)
      - [Bootstrapping from a recovery token](#bootstrapping-from-a-recovery-token)
      - [Feature flags](#feature-flags)
    - [Events](#events)
  - [Building the Widget](#building-the-widget)
    - [The `.widgetrc` config file](#the-widgetrc-config-file)
    - [Build and test commands](#build-and-test-commands)
  - [Contributing](#contributing)
```

3. I'm thinking if we shall move `Browser support` to the end and merge `Need help?` with `Contributing` since both have similar content?

```
* [Getting started](#getting-started)
* [Usage guide](#usage-guide)
* [API Reference](#api-reference)
* [Building the Widget](#building-the-widget)
* [Browser support](#browser-support)
* [Contributing](#contributing)
* [Need help?](#need-help)
```

4. I'm fine to only keep the link to forum and address content as follow ups.

**Comment by jmelberg-okta** [comment]
Great recommendations! I'll use a TOC generator to ensure it is always in sync.

> Regarding the levels, given the complexity of the doc, 3 levels seems good to me unless we move `API reference` to a separated markdown file. Thoughts?

I'd push to keep `API Reference` within the primary README file, as this is the content that is frequently deep-linked to. Second, I agree that a maximum of **3** levels deep is good for our TOC.  Essentially:

```
- API Reference
    - Install
      - Using the Okta CDN
      - ...
```

Any deeper will clutter our TOC.

> I'm thinking if we shall move `Browser support` to the end and merge `Need help?` with `Contributing` since both have similar content?

+1 for moving `Browser Support` to the end.

To me, `Need help?` and `Contributing` are currently two separate use cases. With `Need help?`, we're pointing developers to either the forum (general questions) or the Issues tab (bugs) to ensure we can help them the best way. While `Contributing` is strictly commit message guidelines.

I'm working toward a model similar to [Angular's CONTRIBUTING](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#issue) file, where it groups together getting help, commit message guidelines, etc. I'll hold off on the `Need help?` section and plan to include it when restructuring our contributing file.

**Comment by haishengwu-okta** [comment]
@jmelberg-okta I'm seeing you break ToC into two part, one at top and one for API reference. 
curious if were both auto-generated and how did you manage to keep them in two places?
why would you prefer to keep separated rather in one place?

**Comment by jmelberg-okta** [comment]
@haishengwu-okta -

Apologies, I forgot to include that reasoning in my last comment.

When I was originally thinking about this, I was expecting to have one **primary** TOC that will include basic navigation throughout this README. As proposed, this will include:

```
Getting started
Usage guide
API Reference
Building the Widget
Browser support
Contributing
```

In the future, the following will be available:

```diff
+ Release status
Getting started
Usage guide
+ Configuration reference
API Reference
Building the Widget
Browser support
Contributing
```

For all method signatures, it made sense to group these in a second TOC - similar to what is nested under [API Reference](https://github.com/okta/okta-signin-widget/blob/b9a797f87390b10db994a823cc0decdc79006867/README.md#api-reference). This will allow readers to easily jump to a needed method.

We lose out on the ability to auto-generate the TOC, but the navigation is a lot more intuitive in my opinion.

Alternatively - we could omit the secondary TOC as other libraries do, yet still provide headers for the method signatures to be deep-linked to. I don't necessarily have a preference.

@nbarbettini Thoughts?

**Pull request merged**
