### PR TITLE
Gen2: Don't save username from failed IDX transaction and don't prefill it to reset password form and enroll form

### PR DESCRIPTION
**Pull request by denysoblohin-okta**
## Description:

Remove unnecessary logic to populate user's email into password recovery form if user was trying to login before clicking on "Forgot password?"
This logic was introduced by [PR #3648 (Don't save failed transaction on identify form)](https://github.com/okta/okta-signin-widget/pull/3648/files#r1636667036) just to fix monolith tests, but now it's not necessary after https://github.com/atko-eng/okta-core/pull/100667

## PR Checklist

- [x] Have you verified the basic functionality for this change?
- [ ] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [x] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [x] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-797799](https://oktainc.atlassian.net/browse/OKTA-797799)

### Screenshot/Video:

Before:

https://github.com/user-attachments/assets/e1254c5b-ddc1-4c95-b7ed-7593a6dd1ac0

https://github.com/user-attachments/assets/f453dbaa-e18d-43ee-8f46-140794896718

After:

https://github.com/user-attachments/assets/d050c5d2-0ebe-4881-a651-c3ca435b15c7

https://github.com/user-attachments/assets/d7b3d680-796a-4fed-a2ca-6e83666d52f4

### Downstream Monolith Build:

https://bacon-go.aue1e.saasure.net/commits?artifact=monolith&page=1&pageSize=6&sha=8b4a49618fd0adfb48642df6eb73c13c45402ad6&tab=main

### CODE REVIEW

**Comment by lesterchoi-okta** [comment]
isolated first commit (e62e14dbf43d66f6ec35cce8c83750ed554df26a) on https://github.com/okta/okta-signin-widget/pull/3707

**Review by trevoring-okta — DISMISSED** [review]
Code changes LGTM, we should just do another sanity check downstream after SIW `7.22` goes into monolith with your test fixes before we merge this 👍

**Review by shawyu-okta — APPROVED** [review]
Rebase onto `7.23` and post a green downstream build before merging

**Review by shawyu-okta — APPROVED** [review]

**Comment by shawyu-okta** [comment]
We're trying something new with commit messages to make releasing the widget simpler, so use a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) type message like this when merging in CI:
```
fix(oie): username should not be prefilled in reset password and enroll forms
```

**Pull request merged**
