### PR TITLE
Okta 511637 fix whitespace trimming and update courage imports

### PR DESCRIPTION
**Pull request by LazarVuckovic-okta**
## Description:

- Fixes issue with trimming whitespace from the beginning and end of Password field value when the Show Password icon is clicked.
- Pulls in latest Courage changes.
- Fixes Handlebars imports to import only what is needed by SIW.

## PR Checklist

- [x] Have you verified the basic functionality for this change?
- [x] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [x] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [x] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-511637](https://oktainc.atlassian.net/browse/OKTA-511637)

### Reviewers:

@jakebacher2-okta 

### Screenshot/Video:

https://okta.box.com/s/4okw5hpj83uwt6lto7eosomq0890bayu

### Downstream Monolith Build:

https://bacon-go.aue1e.saasure.net/commits?artifact=monolith&branch=d16t-okta-signin-widget-249f499-6409053b&page=1&pageSize=6&tab=main

### CODE REVIEW

**Comment by jakebacher2-okta** [comment]
Just confirming the correct merge version, do we want this in `master`? Customer was on `6.4.2` at the time the JIRA was filed (June 2022)

Now they are on `7.3.1` (Splunk logs from March 7).

**Comment by LazarVuckovic-okta** [comment]
@jakebacher2-okta thank you for checking!
With the nature of the change, the SIW team wanted this to be in a monthly release. We will be asking the client to upgrade to the latest SIW to get the fix

**Review by michaeltamaki-okta — COMMENTED** [review]
LGTM -- can we just double check that there's no rendering issues because of the removed handlebars helpers?

**Review by aarongranick-okta — APPROVED** [review]

**Comment by LazarVuckovic-okta** [comment]
> LGTM -- can we just double check that there's no rendering issues because of the removed handlebars helpers?

I did not see any rendering issues and all the tests passed (both SIW and downstream builds)

**Review by jakebacher2-okta — APPROVED** [review]

**Review by shuowu-okta — APPROVED** [review]

**Pull request merged**
