### PR TITLE
fix: Fixes inline style-src CSP issue in SMS/Call enroll and MFA verify

### PR DESCRIPTION
**Pull request by LazarVuckovic-okta**
## Description:

Updates the properties files to remove inline styles and adds CSS rules to maintain the existing behavior, in order to address an inline style-src CSP violation in the SMS/Call enroll screens, as well as MFA verify.

Addresses the issue shown in the following video: https://okta.box.com/s/ksxyera0eqj59gpd0hxv111a98aix6ff

Fixes problems on the following paths:
```
signin/enroll/okta/sms
signin/enroll/okta/call
signin/verify/okta/sms
signin/verify/okta/call
```

## PR Checklist

- [x] Have you verified the basic functionality for this change?
- [x] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [x] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [x] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-572016](https://oktainc.atlassian.net/browse/OKTA-572016)

### Reviewers:

@indirathirumalaimurugan-okta 

### Screenshot/Video:

Enroll SMS/Voice fix:
https://okta.box.com/s/n3byhkm0n2qw2a5x6ub0if78rz3nkyde

Verify SMS/Voice fix:
https://okta.box.com/s/a75bwgdhc5x12kavk2vpsa4ildhoviid

### Downstream Monolith Build:

https://bacon-go.aue1e.saasure.net/commits?artifact=monolith&branch=d16t-okta-signin-widget-bf3092c-63e2d4e4&page=1&pageSize=6&sha=9258fbb6fc6f46063afa93903b0326ab984c2608&tab=main

### CODE REVIEW

**Review by indirathirumalaimurugan-okta — APPROVED** [review]
lgtm

**Review by glenfannin-okta — APPROVED** [review]
LGTM

**Review by nikhilvenkatraman-okta — APPROVED** [review]
i18n changes look good. Changes to all language files are expected as it is changing params 
https://oktawiki.atlassian.net/wiki/spaces/eng/pages/741293778/Requesting+and+Receiving+Translations+i18n+and+l10n#Updating-existing-param-value/-html-attributes-in-a-resource-bundle

**Review by nikhilvenkatraman-okta — CHANGES_REQUESTED** [review]
@LazarVuckovic-okta  please make sure login_ok_PL.properties is also updated 

https://github.com/okta/okta-signin-widget#utilizing-pseudo-loc

**Review by nikhilvenkatraman-okta — APPROVED** [review]

**Review by ganeshsomasundaram-okta — APPROVED** [review]
looks good to me! I'll leave the approval to the siw codeowners.

**Review by mihaiiacob-okta — APPROVED** [review]

**Pull request merged**
