### PR TITLE
:bug: Fix scroll bug inside login widget

### PR DESCRIPTION
**Pull request by iuriipetrov-okta**
Fix scroll bug inside login widget container

Resolves: OKTA-182947

### CODE REVIEW

**Comment by iuriipetrov-okta** [comment]
Reviewers: @santhoshbalakrishnan @upteam-okta

**Comment by santhoshbalakrishnan** [comment]
@iuriipetrov-okta Can you add screenshare of the behavior?

**Comment by iuriipetrov-okta** [comment]
@santhoshbalakrishnan I couldn't reproduce it by myself but I saw the bug in live screensharing with Paul Stiniguta. You can check a screenshot from the task:
image

**Comment by santhoshbalakrishnan** [comment]
Taking offline.

**Comment by iuriipetrov-okta** [comment]
@santhoshbalakrishnan 
Before:
scroll_before

After:
scroll_after

**Comment by santhoshbalakrishnan** [comment]
@nikhilvenkatraman-okta We had to change the class name from `content` to `content-container` around registration footer since there is another class called `content` and that brings in unnecessary styles, which break existing styles. Wanted to check with you to see if there are more instances of `content` that need changing.

**Comment by nikhilvenkatraman-okta** [comment]
@santhoshbalakrishnan changes look good, as this is only changing the classname of the container from `content` to `content-container` within `registration-container`.

**Pull request merged**
