### PR TITLE
:arrow_up: update i18n version to 26.21.0

### PR DESCRIPTION
**Pull request by manueltanzi-okta**
:arrow_up: update i18n version to 26.21.0

update i18n version to 26.21.0

Resolves: [OKTA-119633](https://oktainc.atlassian.net/browse/OKTA-119633)

@mauriciocastillosilva-okta

### CODE REVIEW

**Comment by manueltanzi-okta** [comment]
@mauriciocastillosilva-okta change to the release version

**Comment by manueltanzi-okta** [comment]
@mauriciocastillosilva-okta I need to merge another PR for okta-sign-in-widget relative to the custom expired password flow that needs those 2 i18n changes, if not travis will not pass the tests that I have added, because they check that those 2 new properties are showed correctly in the new route.
@hor-kanchan-okta

**Comment by mauriciocastillosilva-okta** [comment]
If that is the case, then you should cherry-pick this commit into that PR, so we have one PR that works by itself.

**Comment by manueltanzi-okta** [comment]
@mauriciocastillosilva-okta will do it

**Comment by mauriciocastillosilva-okta** [comment]
Feel free to have two commits in that other PR, one for your code changes and one for updating i18n. At the end, when everything is good, we can squash them in github directly

**Pull request closed without merging**
