### PR TITLE
fix(docs): Minor edits to documentation

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Description:

This PR supplies minor edits to fix a few typos in the documentation.

In addition, noticed a typo in one of the issue templates, so threw that in also.

PS: I've not signed the Okta CLA, but believe this falls in the ["obvious fix" (typo) category](https://developer.okta.com/cla/).

## PR Checklist

- [x] Have you verified the basic functionality for this change?
- [x] no / Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [x] nope :) / Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [x] no / Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [x] no / Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

n/a, external PR

- [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by adamdmharvey** [comment]
cc @joedelnano-okta another one!

**Comment by adamdmharvey** [comment]
Bump on this one.  Thx all! 👍🏻

**Comment by adamdmharvey** [comment]
Thought I'd throw in another bump

**Comment by adamdmharvey** [comment]
Hey @glenfannin-okta , saw you pretty active recently; any chance you could take a peek? Thanks!

**Comment by glenfannin-okta** [comment]
@adamdmharvey Thank you so much for the contribution.

Internal Ref: OKTA-718823

**Comment by denysoblohin-okta** [comment]
Thanks for the PR.
I moved the changes to #3608 to pass CI and merged it.

**Pull request closed without merging**
