### PR TITLE
Backport 5.5.2

### PR DESCRIPTION
**Pull request by haishengwu-okta**
## Description:

Backports `5.5.2` to `main`

- OKTA-382383 fix failing tests due to aria attribute moving da9505a
- feat: do not automatically redirect to IDP on initial load  a83fe0a
- fix: rename sign-out to back-to-sign-in  4c361d6
- OKTA-382782: Variable IDX Challenge Polling  0804ec2
- Update courage dist to support showCancelBeforeSave  084b196
- chore: Adds i18n for symantec on OIE  a14f381
- fix: poll view in OIE  c3cd9ed
- fixes CSP regression  53da412
- Remove stateHandle from fingerprinting  3d01fca
- update AppState.shouldReRenderView() to ignore 'stateHandle' data OKTA aa0d196
- fix: checks for correct error code during verification of rsa / on-pr ffa37dc

## PR Checklist

- [ ] Have you verified the basic functionality for this change?
- [ ] Added unit tests?
- [ ] Added e2e tests
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Issue:

- OKTA-385741

### CODE REVIEW

**Review by gowthamidommety-okta — APPROVED** [review]
my commit backport lgtm!

**Comment by magizh-okta** [comment]
My change lgtm 👍

**Comment by worldleelavivat-okta** [comment]
my change is there. lgtm

**Review by jmelberg-okta — APPROVED** [review]
Cherry-pick of changes LGTM!

Lots of great work from the last week or so!

**Pull request closed without merging**
