### PR TITLE
:bug: Change border color on focused input

### PR DESCRIPTION
**Pull request by eugenebakaiev-okta**
Add variable for focused input color
Resolves: OKTA-114249

### CODE REVIEW

**Comment by eugenebakaiev-okta** [comment]
inputfocus mov

**Comment by eugenebakaiev-okta** [comment]
@hor-kanchan-okta please take a look

**Comment by hor-kanchan-okta** [comment]
After you lost focus, he Username only has the blue border on the top. Is it just the video?

**Comment by eugenebakaiev-okta** [comment]
@hor-kanchan-okta, yes it's just a video. When input loses focus border changes color completely

**Comment by eugenebakaiev-okta** [comment]
@mauriciocastillosilva-okta please take a look

**Pull request merged**
