### PR TITLE
Disable Register button when password complexity errors are shown

### PR DESCRIPTION
**Pull request by nikhilvenkatraman-okta**
🌱  Disable Register button when password complexity errors are shown  

screen shot 2017-10-18 at 11 27 04 pm

Resolves: OKTA-145577

@hor-kanchan-okta @richardheng-okta

### CODE REVIEW

**Comment by nikhilvenkatraman-okta** [comment]
@hor-kanchan-okta updated this PR to have only changes for OKTA-145577

**Comment by nikhilvenkatraman-okta** [comment]
@hor-kanchan-okta PR updated

**Comment by hor-kanchan-okta** [comment]
I wonder how this work with the required fields.
If I have required field but is empty. Will the "register" button be disabled?

**Comment by nikhilvenkatraman-okta** [comment]
Good catch. I just realized that too. I have to change the listener to also fire the toggle method when model fires "invalid" event. When the form has required fields empty the invalid event is fired. That should do it i guess.

```javascript
        form.listenTo(this.model, 'disableRegister invalid', function(){
           toggleRegisterButton(true);
         });

```

**Comment by nikhilvenkatraman-okta** [comment]
https://okta.box.com/s/l1lvq4v9m2uh26dz4sklt7t3mh5atytu

**Comment by nikhilvenkatraman-okta** [comment]
@hor-kanchan-okta added video to show  required fields use case along

**Pull request closed without merging**
