### PR TITLE
password icon update

### PR DESCRIPTION
**Pull request by anipendakur-okta**
## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:
image
image

### Reviewers:
@haishengwu-okta @gowthamidommety-okta @vincentvoong-okta 

### Issue:

- [OKTA-306103](https://oktainc.atlassian.net/browse/OKTA-306103)

### CODE REVIEW

**Comment by gowthamidommety-okta** [comment]
Can you please do a quick test with this change in v1 as well?

**Comment by vincentvoong-okta** [comment]
This looks good.

**Comment by anipendakur-okta** [comment]
> hmm, don't you need to change CSS given image name changed/

I have not changed the name, I have replaced the icons.

**Comment by haishengwu-okta** [comment]
the git diff looks like you rename files..

**Comment by anipendakur-okta** [comment]
> the git diff looks like you rename files..

I thought there will be an arrow separating the two filenames if I renamed it (old file name --> new file name), in this case it shows Bytes changed since this is a binary file that changed as I replaced the contents of the image file.

**Comment by gowthamidommety-okta** [comment]
Tested verify and factor dropdown on v1

Screen Shot 2020-06-25 at 2 28 41 PM

Screen Shot 2020-06-25 at 2 31 59 PM

@anipendakur-okta are these the only flows the icon shows?

**Pull request merged**
