### PR TITLE
fix: Fixes tests and css

### PR DESCRIPTION
**Pull request by manueltanzi-okta**
### Description

- Fixes some failing tests after rebase
- Fixes protractor failing tests
- Fixes css bug

### Screenshots

**BEFORE:**

Screen Shot 2019-07-01 at 3 19 08 PM

**AFTER:**

Screen Shot 2019-07-02 at 3 52 21 PM
Screen Shot 2019-07-02 at 3 52 03 PM
Screen Shot 2019-07-02 at 3 50 39 PM

### Reviewers

@haishengwu-okta @robertdamphousse-okta @vijetmahabaleshwar-okta

### CODE REVIEW

**Comment by haoyuli-okta** [comment]
@manueltanzi-okta By looking at mocked UI of After, I believe we should not have `Enter Code` over there. If you look back to the jira again, `Enter Code` is listed within the textbox

**Comment by manueltanzi-okta** [comment]
cc: @alexdahl-okta or @maggielaw-okta , can you take a look as well? Thank you!

**Comment by maggielaw-okta** [comment]
@manueltanzi-okta thanks for the invitation to review. (@alexdahl-okta is on PTO, FYI.) 

It's great to see the alignment issue fixed. How easy would it be to apply an add'l fix to these form elements to improve a11y for focus states? See https://oktainc.atlassian.net/browse/OKTA-210992 and the attached screenshot for similar fixes made on the SIW.
Focus States (OKTA-210992)

**Comment by vijetmahabaleshwar-okta** [comment]
> @manueltanzi-okta By looking at mocked UI of After, I believe we should not have `Enter Code` over there. If you look back to the jira again, `Enter Code` is listed within the textbox

@haoyuli-okta - The accessibility changes we've made move the text out of the text box. We will have labels instead which is as shown in the screenshot.

**Comment by maggielaw-okta** [comment]
Agree that the positioning of the Enter Code label is confusing. Is there a reason we can't swap the field and button?
image

**Comment by manueltanzi-okta** [comment]
@maggielaw-okta Good point, swapped button and field!
For the focus one, is a bit out of scope for this, and I would like to limit further changes since siw 3.0 has been already thoroughly tested.
I created a JIRA for that: https://oktainc.atlassian.net/browse/OKTA-236470

**Pull request merged**
