### PR TITLE
removes route logic for /signin/register on V2

### PR DESCRIPTION
**Pull request by aarongranick-okta**
## Description:
Removes logic based on the browser location in V2. This logic interferes with proper implementation of this feature server-side.

Embedded widgets can use the `flow` configuration option to achieve the same result.

### Issue:

- [OKTA-462003](https://oktainc.atlassian.net/browse/OKTA-462003)

### CODE REVIEW

**Review by haishengwu-okta — APPROVED** [review]
Probably can also clean the properties? https://github.com/okta/okta-signin-widget/pull/1782/files#diff-391ef791333e16bfeed711da3def133ca2471a6ebbe1e917ecc61330a1530fe3

**Review by pradeepdewda-okta — APPROVED** [review]
neat

**Comment by aarongranick-okta** [comment]
> Probably can also clean the properties? https://github.com/okta/okta-signin-widget/pull/1782/files#diff-391ef791333e16bfeed711da3def133ca2471a6ebbe1e917ecc61330a1530fe3

I am thinking we want to leave this key because the backend will still want to use the widget to display an error in the case that registration is not enabled. As long as backend uses the previous key `oie.registration.is.not.enabled` it should have translations.

**Review by moushmibanerjee-okta — APPROVED** [review]
LGTM.

**Pull request closed without merging**
