### PR TITLE
OKTA-379163 Change OIE remember me text

### PR DESCRIPTION
**Pull request by haoyuli-okta**
## Description:
image

## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Issue:

- [OKTA-379163](https://oktainc.atlassian.net/browse/OKTA-379163)

### CODE REVIEW

**Review by haishengwu-okta — APPROVED** [review]

**Comment by anipendakur-okta** [comment]
Can we actually change this for both OIE and V1? Instead of decoupling? Can we push back on product?

Imho, if this gets changed on OIE only, sooner or later V1 change request will arise too. Just want to make sure that's not the case. cc: @haoyuli-okta

**Comment by anipendakur-okta** [comment]
> Can we actually change this for both OIE and V1? Instead of decoupling? Can we push back on product?
> 
> Imho, if this gets changed on OIE only, sooner or later V1 change request will arise too. Just want to make sure that's not the case. cc: @haoyuli-okta

I just spoke with @jadsiblini-okta and @haoyuli-okta , The meaning of the remember me checkbox (functionality) is different from V1. It makes sense to have `Remember Me` in V1 and `Keep me signed in` in OIE. Hence this is good to go.

**Review by anipendakur-okta — APPROVED** [review]
LGTM

**Review by jadsiblini-okta — APPROVED** [review]
LGTM

**Review by anipendakur-okta — CHANGES_REQUESTED** [review]
Please rebase it to `5.4`

**Review by anipendakur-okta — APPROVED** [review]

**Pull request closed without merging**
