### PR TITLE
Include only the i18n files that are needed by the Sign in Widget

### PR DESCRIPTION
**Pull request by Ujjwalreddy-okta**
OKTA-91782

### CODE REVIEW

**Comment by Ujjwalreddy-okta** [comment]
No new files added. Just modified files under `node_modules/@okta/i18n`

**Comment by sergiymelnyk-okta** [comment]
LGTM

**Comment by rchild-okta** [comment]
It does look like there are quite a few new files added. Can you ask @ravikanodia-okta what he did when he imported the original step? Was there a manual step where he removed them from the commit? 

On further reflection, I think the ideal output is to only checkin the json/login* files (i.e. no properties, no requirejs if we're not using them, and no .json files that are not login related).

**Comment by Ujjwalreddy-okta** [comment]
Looks like @ravikanodia-okta commit - https://github.com/okta/okta-signin-widget/pull/63 included all the files. I will modify the logic to only include the needed files.

**Comment by Ujjwalreddy-okta** [comment]
This includes just the login.js/country.js files under requirejs folder and login*.properties and country*.properties in properties folder.

**Comment by rchild-okta** [comment]
lgtm 🚀

**Pull request merged**
