### PR TITLE
fix: ie11 fromEntries issue - OKTA-344863

### PR DESCRIPTION
**Pull request by shuowu**
## Description:

Fixes IDX ie11 compatibility issue

This PR updates the fix from IDX (https://github.com/okta/okta-idx-js/pull/35)

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Issue:

- [OKTA-344863](https://oktainc.atlassian.net/browse/OKTA-344863)

### CODE REVIEW

**Comment by swiftone** [comment]
This is updating based on the idx--js master branch, yes?

**Comment by shuowu** [comment]
@swiftone Yes, based on master of idx-js.

**Review by swiftone — APPROVED** [review]

**Review by swiftone — APPROVED** [review]

**Review by swiftone — APPROVED** [review]

**Review by aarongranick-okta — APPROVED** [review]
Looks good, of course it must pass all tests (last time we had this issue if I remember correctly it broke internationalization, but I believe there is a test to protect for this).

Also, should base this PR off `master`. We are doing release for version `5.1` tomorrow.

**Review by brettritter-okta — APPROVED** [review]

**Comment by shuowu** [comment]
Looks like lots of diffs from `master`, let me create a new PR.

**Pull request closed without merging**
