### PR TITLE
login_nl_NL properties fix typo enroll.totp.enterCode

### PR DESCRIPTION
**Pull request by Styxxy**
## Description:
fix typo for Dutch language in login properties, enroll.totp.enterCode (EVoer ... in -> Voer ... in)

## PR Checklist
- [x] Have you verified the basic functionality for this change? (testen in private Okta sandbox)
- [x] Added unit tests? (n/a)
- [x] Added e2e tests (n/a)
- [x] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)? (n/a)

### CODE REVIEW

**Comment by Styxxy** [comment]
For some reason the build failed. No idea why though.

**Comment by Styxxy** [comment]
@aarongranick-okta Does anyone look at PR's?

**Comment by aarongranick-okta** [comment]
@santhoshbalakrishnan Could you take a look?

**Comment by haishengwu-okta** [comment]
Fixed in https://github.com/okta/okta-signin-widget/pull/1444

**Pull request closed without merging**
