### PR TITLE
Maps brand colors to override MUI-odyssey theme

### PR DESCRIPTION
**Pull request by shawyu-okta**
## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [x] Added unit tests?

- [ ] Added e2e tests

- [x] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

- Did you verify the change by running downstream monolith artifacts? (YES | NO | UNSURE)

### Issue:

- [OKTA-514615](https://oktainc.atlassian.net/browse/OKTA-514615)

### CODE REVIEW

**Review by lesterchoi-okta — COMMENTED** [review]
Does this need tests?
Looks trivial now but we can make sure the mapping works if we have to update the `brand` object.

**Comment by shawyu-okta** [comment]
> Does this need tests?
> Looks trivial now but we can make sure the mapping works if we have to update the brand object.

I didn't add tests since the previous mapping didn't have tests (we did test the "derive colors" function) but I agree that having some tests would help in the scenario you pointed out. I'll add some simple assertions for that.

**Comment by shuowu-okta** [comment]
maybe migrate theming test from v3/testcafe to jest, and add additional tests there if it's not too much work

**Review by lesterchoi-okta — APPROVED** [review]
Leaving the testing decision up to you. Maybe we can add it when ODS theming stabilizes

**Comment by shawyu-okta** [comment]
Migrating the e2e test for theming is a good idea - I looked and it seems quite doable, but we would still have to keep it skipped since the components within the widget aren't reflecting the theme in MUI yet, so even if I migrated it they would still be skipped. Because of that I want to hold off migrating the test until I can see it pass.

**Comment by lesterchoi-okta** [comment]
Can you create a story for that?

**Comment by shawyu-okta** [comment]
@lesterchoi-okta yup, i have added a comment to the JIRA in the code as well: https://oktainc.atlassian.net/browse/OKTA-519086

**Pull request merged**
